### ISSUE TITLE
Strange Errors

### ISSUE THREAD

**Issue by kaiwei** [hoostus/beancount-ynab5#2]
Just tried the script but got some strange error messages which looks like server side issues. Any hints?

> Traceback (most recent call last):
>   File "ynab.py", line 325, in <module>
>     budget, ynab_accounts, ynab_category_groups, ynab_categories, ynab_transactions = fetcher(args.ynab_token, args.budget, args.since)
>   File "ynab.py", line 241, in get_ynab_data_async
>     budget, accounts, category_groups, categories, transactions = loop.run_until_complete(future)    File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
>     return future.result()
>   File "ynab.py", line 216, in run
>     budget = budget_from_json(budget_name, d['data']['budgets'])
>   File "ynab.py", line 59, in budget_from_json
>     b = json_budgets.values()[0]
> AttributeError: 'list' object has no attribute 'values'

**Comment by hoostus** [comment]
It sounds like the response to the /budgets YNAB API isn't returning what the script is expecting. It is expecting a dictionary that contains an array. That is:

`{"data": "budgets": []}`

Can you check what it is returning for you? If you have have curl and jq installed you can run this and let me know what the results are like.

`curl -H "Authorization: Bearer PUT_YOUR_API_KEY_HERE" https://api.youneedabudget.com/v1/budgets | jq .data.budgets`

**Comment by adamgibbins** [comment]
I get this too

```
% curl -sSH "Authorization: Bearer $token" https://api.youneedabudget.com/v1/budgets | jq .data.budgets
[
  {
    "id": "REMOVED",
    "name": "Budget",
    "last_modified_on": "2020-06-07T13:03:56+00:00",
    "first_month": "2019-06-01",
    "last_month": "2020-06-01",
    "date_format": {
      "format": "YYYY-MM-DD"
    },
    "currency_format": {
      "iso_code": "GBP",
      "example_format": "123,456.78",
      "decimal_digits": 2,
      "decimal_separator": ".",
      "symbol_first": true,
      "group_separator": ",",
      "currency_symbol": "£",
      "display_symbol": true
    }
  }
]
```

**Comment by hoostus** [comment]
Sorry about the delay, now that it is the weekend I've fixed this. Try pulling the latest version and it should work now.

**Comment by adamgibbins** [comment]
Works, thanks 👍
