### ISSUE TITLE
Request: Get transactions by account_id

### ISSUE THREAD

**Issue by kstockk** [hoostus/beancount-ynab5#4]
Hi,

Wondering if I can make a request to get transactions by specifying an account_id instead of getting all transactions for all accounts.

Use-case: I only use this for on_budget accounts and want to exclude tracking accounts.

Thanks

**Comment by hoostus** [comment]
Sure this seems reasonable. Try the new version I just pushed and let me know if that works for your use case.

**Comment by kstockk** [comment]
Thanks so much! Working exactly how I wanted it.
